- .github/workflows/dependency-review.yml
> [JE]: Added Dependency check for workflows

- src/lib/_services/authService.ts
- src/routes/movies/[movieId]/+page.svelte
Fixed an error with the youtube player,
made user always be locked-in (needs to be changed in prod)
> [JE]: Latest implemenation of userdashboard

- src/_ui/templates/cinemahall.svelte
- src/_ui/templates/selSeatOverview.svelte
- src/_ui/templates/timer.svelte
- src/routes/seatselection/+page.svelte
> [JE]: Seatselection correction

- .github/workflows/cd.yml
- package.json
- pnpm-lock.yaml
- src/_ui/layout/_mainpage/mainPageMovieRow.svelte
- src/_ui/layout/_mainpage/specialEventTile.svelte
- src/_ui/layout/mainRoundAbout.svelte
- src/_ui/templates/cinemaTile.svelte
- src/_ui/templates/mainCard.svelte
- src/_ui/templates/movieRow.svelte
- src/_ui/templates/specialCard.svelte
- src/routes/+layout.svelte
- src/routes/+page.svelte
- src/routes/tester/+page.svelte
Generalize mainPageElements, give them reasonable names Make everything scalable(iPhone, Laptop)
Removed some unnecessary imports getPictures() for example, I hope there were unnecessary
> [JE]: Mainpage layout, movie row and mainsiteelements

- src/_ui/templates/mainCard.svelte
- src/_ui/templates/movieRow.svelte
- src/routes/+page.svelte
Ensure every movieRow entry has equal size
> [JE]: Fix movieRow

- src/routes/ticketcontrol/+page.svelte
- you can test the qrcode scanner by generating QRcode-Strings using online qrcode-generating tools. 
- for now the QRCode must have the following format: **(qrcode 1, qrcode 2 ... qrcode n)** please use this format as string-text to generate qrcode and test the scanner
- later this can be changed to some randome String
- you can also provide qrcode in the above format in the input-field
closes #73 
closes #74 
closes #75 
closes #76 
closes #77 
closes #70
> scan tickets or provide qrcode manuelly --> ticket-control app

- src/_ui/templates/eventPreview.svelte
- src/_ui/templates/hallCreator.svelte
- src/_ui/templates/hallDropdown.svelte
- src/_ui/templates/imgWithUndertitle.svelte
- src/_ui/templates/mainCard.svelte
- src/_ui/templates/movieSelector.svelte
- src/_ui/templates/previewRow.svelte
- src/_ui/templates/showTimeTool.svelte
- src/_ui/templates/timeRow.svelte
- src/_ui/templates/timer.svelte
- src/routes/admin/mycinemas/add/+page.svelte
- src/routes/admin/myshowings/add/+page.svelte
- src/routes/admin/myshowings/add/+page.ts
- src/routes/seatselection/+page.svelte
- src/routes/seatselection/+page.ts
> [JE]: At this point it doesnt really matter,right?

- src/_ui/layout/_movies/showings.svelte
- src/_ui/layout/cookies.svelte
- src/routes/+layout.svelte
- src/routes/admin/+page.svelte
- src/routes/admin/mymovies/add/+page.svelte
- src/routes/admin/mymovies/preview/[previewId]/+page.svelte
- src/routes/auth/login/+page.svelte
- src/routes/auth/logout/+page.svelte
- src/routes/auth/register/+page.svelte
- src/routes/booking/+page.svelte
- src/routes/confirmation/+page.svelte
- src/routes/dashboard/+page.svelte
- src/routes/locations/+page.svelte
> [JE]: Change all redirects to goto and made workflow happend

- package.json
- pnpm-lock.yaml
- src/_ui/templates/cinemahall.svelte
- src/_ui/templates/drawSeat.svelte
- src/_ui/templates/hallCreator.svelte
- src/_ui/templates/hallDropdown.svelte
- src/_ui/templates/imgWithUndertitle.svelte
- src/_ui/templates/movieSelector.svelte
- src/_ui/templates/priceForCatSetter.svelte
- src/_ui/templates/seatLegend.svelte
- src/_ui/templates/selSeatOverview.svelte
- src/_ui/templates/showTimeTool.svelte
- src/_ui/templates/timeRow.svelte
- src/routes/admin/mycinemas/add/+page.svelte
- src/routes/admin/mygenres/+page.svelte
- src/routes/admin/mylocations/add/+page.svelte
- src/routes/admin/myshowings/add/+page.svelte
- src/routes/admin/myshowings/add/+page.ts
- src/routes/seatselection/+page.svelte
- src/routes/seatselection/+page.ts
- src/routes/tester/+page.svelte
> [JE]: A lot of changes

- src/routes/movies/[movieId]/+page.svelte
- src/routes/movies/[movieId]/+page.ts
> [JE]: Added rating

- src/_ui/templates/cinemahall.svelte
- src/_ui/templates/movieSelector.svelte
- src/routes/admin/myshowings/add/+page.svelte
> [JE]: Small changes

- src/routes/movies/[movieId]/+page.svelte
> [JE]: Fixed Reviews

- src/_ui/layout/_movies/cinemas.svelte
- src/_ui/layout/_movies/showings.svelte
- src/routes/movies/[movieId]/+page.svelte
- src/routes/movies/[movieId]/+page.ts
- src/routes/specialevents/+page.svelte
- src/routes/specialevents/[specialEventId]/+page.svelte
- src/routes/specialevents/[specialEventId]/+page.ts
> Special events

- src/routes/specialevents/[specialEventId]/+page.svelte
> [JE]: SpecialEvents changes

- src/_ui/layout/_movies/showings.svelte
- src/_ui/layout/chatbot.svelte
- src/routes/+layout.svelte
- src/routes/auth/register/+page.svelte
> [JE]: First chatbot :3

- src/_ui/templates/cinemahall.svelte
- src/_ui/templates/drawSeat.svelte
- src/_ui/templates/hallCreator.svelte
- src/_ui/templates/timer.svelte
- src/routes/admin/mycinemas/add/+page.svelte
- src/routes/admin/mygenres/+page.svelte
- src/routes/admin/mylocations/add/+page.svelte
- src/routes/admin/myshowings/add/+page.svelte
- src/routes/movies/+page.svelte
- src/routes/seatselection/[eventId]/+page.svelte
- src/routes/seatselection/[eventId]/+page.ts
- src/routes/tester/+page.svelte
> [JE]: Some chnges

- src/routes/admin/mymovies/add/+page.svelte
- src/routes/auth/login/+page.svelte
- src/routes/auth/logout/+page.svelte
- src/routes/auth/register/+page.svelte
- src/routes/movies/[movieId]/+page.svelte
> Ja nh pull

- src/_ui/templates/cinemahall.svelte
> [JE]: Small change

- src/_ui/templates/priceForCatSetter.svelte
- src/_ui/templates/seatLegend.svelte
- src/_ui/templates/selSeatOverview.svelte
- src/_ui/templates/typeSelector.svelte
> [JE]: Aceeee

- src/_ui/templates/mainCard.svelte
- src/_ui/templates/movieRow.svelte
> [JE]: aceeeee

- src/_ui/templates/movieSelector.svelte
- src/_ui/templates/previewRow.svelte
- src/_ui/templates/selSeatOverview.svelte
- src/routes/admin/mygenres/+page.svelte
- src/routes/admin/myshowings/add/+page.svelte
- src/routes/seatselection/[eventId]/+page.svelte
> [JE]: ACeee

- src/_ui/layout/chatbot.svelte
- src/routes/specialevents/+page.svelte
> [JE]: Lila

- src/_ui/templates/cinemahall.svelte
- src/_ui/templates/selSeatOverview.svelte
- src/_ui/templates/timer.svelte
- src/routes/seatselection/[eventId]/+page.svelte
> [JE]: Elias

- src/_ui/templates/cinemahall.svelte
- src/_ui/templates/hallCreator.svelte
- src/_ui/templates/hallDropdown.svelte
- src/_ui/templates/showTimeTool.svelte
- src/_ui/templates/theatreDropdown.svelte
- src/_ui/templates/timeRow.svelte
- src/_ui/templates/timer.svelte
- src/routes/admin/mycinemas/add/+page.svelte
- src/routes/admin/mygenres/+page.svelte
- src/routes/admin/myshowings/add/+page.svelte
- src/routes/seatselection/[eventId]/+page.svelte
> [JE]: Aceeeeeeeeeeee a lot

- src/routes/seatselection/[eventId]/+page.svelte
> [JE]: Ace sm

- src/_ui/templates/selectedSeatCard.svelte
> [JE]: Some changes, ace

- src/routes/ticketcontrol/+page.svelte
-[bug] Valid and Invalid SVGs of the previous ticket should be gone after swiching between manuel-mode and scanning-mode
-[bug] ticketcontrol not showing correctly on mobile screen
- Using tailiwind CSS for styling
closes: #115
closes: #116 
closes: #132
> Fixing small issues and bugs

- src/_ui/layout/_movies/showings.svelte
- src/routes/booking/[eventId]/+page.svelte
- src/routes/confirmation/[eventId]/+page.svelte
- src/routes/dashboard/+page.svelte
- src/routes/dashboard/+page.ts
- src/routes/movies/[movieId]/+page.svelte
- src/routes/movies/[movieId]/+page.ts
- src/routes/reservation/[eventId]/+page.svelte
- src/routes/specialevents/+page.svelte
- src/routes/specialevents/+page.ts
> [JE]: Goat

- src/_ui/layout/_movies/showings.svelte
- src/_ui/templates/theatreCard.svelte
- src/routes/theatres/+page.svelte
no bug but kein bock auf branch switchen
> [JE] location

- src/_ui/layout/navbar.svelte
- src/_ui/templates/editButton.svelte
- src/_ui/templates/hallCreator.svelte
- src/_ui/templates/movieSelector.svelte
- src/_ui/templates/selSeatOverview.svelte
- src/_ui/templates/showTimeTool.svelte
- src/_ui/templates/theatreDropdown.svelte
- src/_ui/templates/timeRow.svelte
- src/routes/admin/+page.svelte
- src/routes/admin/mycinemas/add/+page.svelte
- src/routes/admin/mygenres/+page.svelte
- src/routes/admin/mylocations/add/+page.svelte
- src/routes/admin/myshowings/add/+page.svelte
> [JE]: Fix seat error

- src/routes/admin/mycinemas/add/+page.svelte
> [JE]: Minor fix, ace

- src/routes/tickets/[eventId]/+page.svelte
- src/routes/ticketvalidation/+page.svelte
> [JE]: Hope

- src/_ui/layout/navbar.svelte
> [JE]: ACE Logger

- src/_ui/layout/_admin/charts/theatreOptions.ts
- src/_ui/layout/_admin/theatres.svelte
- src/lib/randomL.ts
- src/routes/adminv2/+page.svelte
- src/routes/dashboard/+page.svelte
- src/routes/dashboardv2/+page.svelte
> [JE] it is what it is

- src/_ui/layout/_admin/charts/theatreOptions.ts
- src/_ui/layout/_admin/theatres.svelte
> [JE]: New updates

- src/_ui/layout/_mainpage/specialEventTile.svelte
- src/_ui/templates/cinemaTile.svelte
- src/_ui/templates/specialCard.svelte
- src/routes/+page.svelte
- src/routes/+page.ts
Fix overlap and add new specialcard design
> [JE]: Specialevents mainpage

- src/_ui/layout/_mainpage/mainPageMovieRow.svelte
- src/_ui/layout/_mainpage/specialEventTile.svelte
- src/routes/+page.svelte
On mainpage fix links and titles of movie rows
> [JE]: Fix titles

- src/_ui/templates/textMainSite.svelte
- src/routes/search/+page.svelte
- src/routes/specialevents/+page.svelte
- src/routes/specialevents/[specialEventId]/+page.svelte
> [JE]: Minor fixes

- src/_ui/layout/_admin/profileAdmin.svelte
- src/_ui/layout/_admin/theatres.svelte
- src/_ui/layout/_dashboard/logout.svelte
- src/_ui/layout/_dashboard/profile.svelte
- src/_ui/templates/theatreCreate.svelte
- src/routes/adminv2/+page.svelte
- src/routes/dashboardv2/+page.svelte
> [JE] Dashboard done

- src/routes/admin/myshowings/add/+page.svelte
- src/routes/search/+page.svelte
- src/routes/specialevents/+page.svelte
> [JE]: Dániel ist doof
